### ISSUE TITLE
Lester's changes undid Gary's changes

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/Embraer-ERJ-145#1]
...

@IAHM-COL, @FGDATA, @LesterBoffo

**Comment by LesterBoffo** [comment]
If changes were made by me,  they were for better flight handling.  there were many issues with the ERJ145, I try to do sparing changes.  You also couldn't bring this up in the forum where it's easier for me to discuss this?

**Comment by legoboyvdlp** [comment]
I've made a fork, where I have put in Gary's changes -- I'll then have a look at your changes and try to bring them together.

And then after that, have a look myself.

**Comment by CA1012** [comment]
Is this topic done?

**Comment by IAHM-COL** [comment]
I think so.
Check Lego's ERJ145 for the alterantive version

**Comment by CA1012** [comment]
I cant find it on his repo.

**Comment by CA1012** [comment]
Nevermind
